### ISSUE TITLE
does not work cfg file is not created

### ISSUE THREAD

**Issue by BLUBBSON** [searica/MoreVanillaBuildPrefabs#1]
Only bepinex and jotuun are installed
and of course more vanilla builds
But I just get an error message and there is no cfg file

I tested on the server and on the client. Everything was reinstalled to rule out other sources of error

But you create a new character and a new world is possible

error code:

TypeLoadException: Could not load type of field 'MoreVanillaBuildPrefabs.PluginConfig:configSync' (1) due to: Could not load file or assembly 'ServerSync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:ServerSync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

**Comment by searica** [comment]
Hey, thanks for letting me know and providing the error code. I've just uploaded a patched version to Thunderstore. Looks like the issue was caused due to a mismatch in version numbers between the AssemblyInfo.cs file and the version number for BepInEx. 

Please let me know if the updated version (0.1.1) resolves the issue for you and I'll close this issue if it does.

**Comment by BLUBBSON** [comment]
Hey, thanks for the quick response, unfortunately it didn't work, the same problem, only that it no longer works to create a new character and a new world And at least I think the error code has changed a bit


Error code:

[Error : Unity Log] TypeLoadException: Could not load type of field 'MoreVanillaBuildPrefabs.PluginConfig:configSync' (1) due to: Could not load file or assembly 'ServerSync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:ServerSync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()

**Comment by searica** [comment]
Okay, I think I've got it now. Thanks for testing so quickly and letting me know as well.

I was able to reproduce the error you're getting when I downloaded the version from Thunderstore but not when testing with my Debug build of the mod. Turns out that ILRepacker wasn't merging ServerSync successfully prior to creating the Release package for Thunderstore. I tweaked the targets file to fix that and ran a few successful tests with the new version when using an existing character and when making a new character.

I've uploaded Version 0.1.2 with the fix to Thunderstore. Hopefully the fix works this time, please let me know when you get a chance to check if the fix resolves the issue for you as well.

**Comment by BLUBBSON** [comment]
Great, it works now, thank you very much for that ;)
