### ISSUE TITLE
DodgeShortcut plugin title and key config

### ISSUE THREAD

**Issue by meigrafd** [searica/MoreVanillaBuildPrefabs#3]
- DodgeShortcut appears as "Plugin" in BepInEx_ConfigurationManager. 
- Wondering how to change/set the key - your "Useage" (typo) on thunderstore.io is cut off after ", then" where it should be explained
- Your last update (1.0.2) is listed as "Version 1.0.1" in Changelog ;)

**Comment by searica** [comment]
Haha, I guess that's what I get for trying to rush a release before breakfast. Thanks for letting me know.

I've uploaded a new version (on 1.0.5 now because Thunderstore requires an update every time the README is changed) that fixes everything you mentioned and also changed the link in the README to point to the correct github repo. I had remembered to do it for the manifest but forgot for the README. So once this issue is resolved please open any future issues on the repository for DodgeShortctut: https://github.com/searica/DodgeShortcut (no worries about opening this one here as that was my error).

Please let me know if the updated README provides clear enough instructions for configuring the mod.
