### ISSUE TITLE
[Suggestion] Custom user definable categories.

### ISSUE THREAD

**Issue by LunaEversor** [searica/MoreVanillaBuildPrefabs#4]
Currently the only options available are those corresponding to the default vanilla categories. This is useful to those who only want to recategorize into existing categories. However, if you want to separate all of the new pieces added by MoreVanillaBuildPrefabs from those included in the base game, your only real option is to lump them all together under the CreatorShop. The inclusion of user definable categories would aid in the decluttering of the primary ones. A handful of predefined, mod specific categories could also be an option. For example, by attaching a prefix or suffix to the category. Misc MVBP, MVBP Crafting, Building+, etc. 

Alternatively, having some sort of integration with HammerTime, which could then handle the user definable categories. Just a thought.

**Comment by searica** [comment]
Hmm, that is an interesting request. I had not considered that before as the general ethos of the mod is Vanilla+. 

First thought: There was recently a request to improve the ordering of pieces within each category that I plan on looking into after completing some work on a different mod. Would that address your desire to de-clutter things?

Second thought: I'm open to adding custom categories. If I did though, the default configuration would not set any pieces to those custom categories. I'd also have to make sure that the category won't show up in the build table unless a piece has been set to that category, just to prevent cluttering up the hammer build table with empty categories. In the future I'd consider user-defined categories but that would be after a number of other improvements and new features I have planned. 

Please let me know your thoughts when you get a chance.

**Comment by LunaEversor** [comment]
Your first thought would go a long way toward alleviating the issue I think. It's probably a better and more user accessible suggestion than my own. I still feel like having a few custom categories could be helpful. I wouldn't necessarily deem them more important than the general order of things however.

One of the things that made me decide on MoreVanillaBuildPrefabs over the others was the Vanilla+ aspect. The other main one was the fact that out of the three I had tested, this one was the only one which consistently had placement sounds. It helped a lot with immersion.

On a side note, I did find an interesting issue while messing about in the game. It appears that many, if not all of the buildable pieces have their name visible while hovering over them. This includes those which spawn during world creation. Not sure if this behavior was intentional or not. Figured that I'd mention it in case it wasn't. Basically when you run past a rock it'll show "Rock 3", or after you build something it'll show it's name whenever you hover over it.

**Comment by searica** [comment]
Good to know. Thanks for the feedback! I'll look into adding just one extra category for now as I'll be able to implement that faster than improving the ordering within each category. Still planning to improve the ordering, just need to figure out how to approach it in a computationally efficient way while still being somewhat future proof against future updates that add more build pieces. 

In the next update I'll also be changing a lot of the rocks and vegetation pieces to only be available if "CreativeMode" is enabled. While the rocks and vegetation are great to have as options (I love being able to build my own stone henge if I want to), they don't fit the Vanilla+ aspect quite as well as other pieces so I'd rather make it clear that they're not really standard build pieces by placing them under the "CreativeMode" umbrella. Should reduce the number of prefabs added in most use-cases and reduce the clutter as well.

Oh that's lovely to hear that you enjoy the placement sounds! I spent a while coming up with the method I use to fix the missing placement sounds for the pieces added by MoreVanillaBuildPrefabs. Glad that someone else also appreciates the effort.

Regarding the hover text, it's semi-intentional. Some of the pieces added by the mod should have hover text (to match their vanilla counterparts) so I automatically add missing hover text to new pieces. Currently though I haven't come up with an effective filtering method to determine which pieces should actually have hover text though. I think I may just remove the automatically generated hover text for now in the next update and only bring it back after figuring out that filtering method.

**Comment by searica** [comment]
I've released an update that adds a new piece category called "Nature" and changed how CreativeMode works for the mod so it also updates while in-game and users control which pieces are considered CreativeMode pieces based on which category they assign pieces. The update also has a variety of other tweaks and improvements (hover text has been removed as well). 

I still plan on looking into improving the ordering of pieces within each category but that will take more time than I have right now so hopefully this gives you a way to reduce the clutter a bit in the meantime. 

Please let me know what you think after you get a chance to test it out.

**Comment by LunaEversor** [comment]
Sorry for the late reply. I didn't play much last night. I did notice the absence of hover text when I logged in. I had previously logged out near a boulder. Overall, I do believe that the update did help. Thank you for doing it. I'm looking forward to the changes you make once you find the time.

**Comment by searica** [comment]
It's still not user defined categories but now that prefabs added by MVBP are sorted based on the piece grouping, that hopefully reduces the visual clutter in each build category even further. 

Curious what your thoughts are now? If you're happy with it then I'll close this issue for now. Knowing myself I'll probably try to figure out inserting the prefabs from MVBP in between the Vanilla pieces at some point regardless though.

**Comment by LunaEversor** [comment]
I've honestly not had the chance to try it out yet. Most of my day was spent trying to figure out a server issue and what little I did play was mostly spent checking that our mod list worked in survival. I meant to check it out, it just slipped my mind. Sorry about that. I'll be sure to do it when I check out the collision update.

**Comment by LunaEversor** [comment]
I'm pretty happy with the current state of organization. It feels better to navigate. Things appear to be grouped together instead of haphazardly thrown about. Thank you!

**Comment by searica** [comment]
Very welcome! Thanks for helping prompt the change.
