### ISSUE TITLE
Potential issue with vegetation collision.

### ISSUE THREAD

**Issue by LunaEversor** [searica/MoreVanillaBuildPrefabs#5]
I seem to have encountered an issue where the collision being applied to trees, saplings, and bushes is larger than it should be. Gaps that you should be able to traverse, you are unable to. This is very noticeable in areas where there are multiple trees with low hanging branches. You will be unable to pass under them, or in some cases, around them with MoreVanillaBuildPrefabs enabled. Figured that I would let you know.

**Comment by searica** [comment]
Hi Luna, thanks for letting me know. I became aware of a similar issue earlier today and have just released an update that solve resolve the collision issues. Turns out that changing some of the layers so that all the prefabs could be removed with the hammer caused some unintended side effects.

I had intended to release the fix earlier today but it took me a lot longer than I expected to chase down an NRE that a new feature introduced when removing player-built pickables. 

Please let me know if the collision issues are resolved on your end once you get a chance to test out the update.

**Comment by LunaEversor** [comment]
Understandable. Thank you for looking into it. It sure did confuse me at first as it was dark out while I was running through the forest. I had to load a vanilla save to make sure that I wasn't imagining things. I'll be sure to test it out tonight or first thing tomorrow. Thanks again!

**Comment by LunaEversor** [comment]
I logged on for a bit. At a cursory glance, everything appears to be working exactly how I would have expected it to. I didn't notice any wonky collision. If I notice any I'll let you know.

**Comment by searica** [comment]
Glad to hear it seems all right. I've got some other players who have been doing some thorough testing of it without any issues so I'll be closing this issue for now. Feel free to re-open it if you notice anything issues though.
