### ISSUE TITLE
A Few Recipe Issues with "unused" items, Some ClipEverything overrides needed by default

### ISSUE THREAD

**Issue by dreamwraith** [searica/MoreVanillaBuildPrefabs#7]
Hiya,

I found issues with 3 default items that are not normally placeable and/or used in vanilla.

Additionally, I have a list of items that needs a default for "ClipEverything" to be set to true or they do not work.

Patches Needed:

[Pickable_Mushroom_Blue] (this is the small blue mushroom)
Recipe Issue: Always requires Blue Mushroom for recipe in addition to whatever is populated in the Requirements field.

[Pickable_BogIronOre] (the currently unused bog iron pickable ore - the large ore pile works fine)
Recipe Issue: Always requires "Bog" Iron Ore (the unused Orange Iron Ore) for recipe in addition to whatever is populated in the Requirements field.

[Pickable_Meteorite] (the currently unused meteorite pickable ore - the large ore pile works fine)
Recipe Issue: Always requires "Bog" Iron Ore (the unused Orange Iron Ore) for recipe in addition to whatever is populated in the Requirements field.

[piece_dvergr_pole] (smaller version of the standard dvergr town pole)
Recipe Issue: The recipe correctly reflects the Requirements field, but it behaves as if there is some hidden recipe requirement, and won't appear in hammer unless debug mode is enabled with placement cost disabled (eg NoPlacementCost = True).

[GlowingMushroom]
ClipEverything = True
[caverock_ice_pillar_wall]
ClipEverything = True
[caverock_ice_stalagmite]
ClipEverything = True
[CreepProp_entrance1]
ClipEverything = True
[trader_wagon_destructible]
ClipEverything = True
[dvergrprops_pickaxe]
ClipEverything = True
[blackmarble_stair_corner]
ClipEverything = True
[blackmarble_stair_corner_left]
ClipEverything = True

**Comment by dreamwraith** [comment]
[Searica.Valheim.MoreVanillaBuildPrefabs.cfg.zip](https://github.com/searica/MoreVanillaBuildPrefabs/files/13246900/Searica.Valheim.MoreVanillaBuildPrefabs.cfg.zip)
config file for what I am currently using.

**Comment by searica** [comment]
Thank you for this. I've adjusted the clipping settings for every piece except the two stair pieces. For the stairs I adjusted the placementPatch setting as that was the fix I had previously enabled by default and I think it works a bit nicer for building with than letting them clip everything.

Regarding the pickable resource cost requirements: the mod currently forces pickables to always require whatever item the pickable drops in order to build it and it scales the amount based on the world modifiers for how how much that pickable will drop. Now that you point it out that does mean that in some cases it does require resources that are only accessible via console commands. Not sure what the best solution to that would be though.

Finally, the [piece_dvergr_pole] issue. That's a very good catch so thank you for that. I tried out a couple things without success and I don't know what could be causing the issue so I'll look into it tomorrow and get back to you.

**Comment by searica** [comment]
So I figured out the issue with "piece_dvergr_pole". It turns out that the Vanilla prefab already has a piece component and it is set to be disabled, so MVBP never enabled it. Problem is fixed in the newest version on Thunderstore (0.5.0). All of the placement problems are also fixed. The recipe issues for the pickables are unchanged and I have made a note of them in the mod's README. I'm currently unsure of how I want to handle that but am open to suggestions.
